#mongodb
server.id=1
server.log.display=false
server.port=14444
mongodb.port=27017
mongodb.bat=false
mongodb.host=localhost
mongodb.dbname=admin
mongodb.user=admin
mongodb.password=123456
websocket.host=ws://localhost
websocket.port=8020
game.upgrade.percent.add=0
game.store.discount=0

#rmi
server.rmi.port=10000
server.rmi.host=localhost

#baotritudong
server.maintenance.hour=0
server.maintenance.minute=0

#shinwa
game.shinwa.active=true
game.server.maxLV=-1
game.shinwa.fee=50000
game.shinwa.discount=10
game.shinwa.max=10000
game.shinwa.player.max=20
game.arena.active=true
game.login.limit=5000
game.trade.limit=10
game.quantity.display.max=30000
server.notification="a"
game.server.exp=5
threadPoolSize=50
scheduledPoolSize=20
client.data.size.max=1024
game.event=com.nsoz.event.TrungThuNew
server.pass.admin=
server.host.admin=
game.data.version=86
game.item.version=73
game.map.version=4
game.skill.version=20
