#database
nsoz.database.driver=com.mysql.cj.jdbc.Driver
nsoz.database.port=3306
nsoz.database.host=localhost
nsoz.database.name=nso_test
nsoz.database.user=root
nsoz.database.pass=
nsoz.database.min=50
nsoz.database.max=5000
nsoz.database.lifetime=1200000
nsoz.database.idleTimeout=600000
nsoz.database.log=false
nsoz.database.baotri=true
