/** Giao diện của bảng tra hồi ức. Tách riêng cho khỏi lẫn với phần máy chủ. */
public final class TrangHoiUc {

    private TrangHoiUc() {
    }

    public static final String HTML = "<!doctype html><html lang=vi><meta charset=utf-8>"
        + "<meta name=viewport content='width=device-width,initial-scale=1'>"
        + "<title>Kho vật phẩm — bản hồi ức</title><style>"
        + ":root{--nen:#15171c;--the:#1d2025;--vien:#2f333b;--chu:#e6e8eb;--nhat:#9aa0a6;"
        + "--xanh:#8ab4f8;--xanhnen:#1e2a3d;--do:#f28b82}"
        + "*{box-sizing:border-box}body{margin:0;background:var(--nen);color:var(--chu);"
        + "font:14px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}"
        + "header{position:sticky;top:0;background:var(--the);border-bottom:1px solid var(--vien);"
        + "padding:12px 16px;display:flex;gap:10px;align-items:center;flex-wrap:wrap;z-index:9}"
        + "h1{font-size:16px;margin:0 12px 0 0}"
        + "input,select{padding:7px 10px;border:1px solid var(--vien);border-radius:7px;"
        + "background:var(--nen);color:var(--chu);font:inherit}"
        + "input#tim{width:230px}"
        + "button{padding:6px 12px;border:1px solid var(--vien);border-radius:7px;background:var(--the);"
        + "color:var(--chu);font:inherit;cursor:pointer}button:hover{border-color:var(--xanh);color:var(--xanh)}"
        + ".luoi{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:10px;padding:14px}"
        + ".mon{border:1px solid var(--vien);border-radius:10px;padding:11px;background:var(--the)}"
        + ".mon:hover{border-color:var(--nhat)}"
        + ".dau{display:flex;gap:10px;align-items:flex-start}"
        + ".anh{width:40px;height:40px;flex:0 0 40px;image-rendering:pixelated;object-fit:contain;"
        + "border:1px solid var(--vien);border-radius:7px;background:var(--nen)}"
        + ".ten{font-weight:600}.the-nho{display:inline-block;font-size:11px;color:var(--nhat);"
        + "border:1px solid var(--vien);border-radius:20px;padding:1px 7px;margin-right:4px}"
        + ".mota{font-size:12px;color:var(--nhat);font-style:italic;margin:5px 0}"
        + "ul{margin:6px 0 0;padding-left:17px;font-size:12.5px}li{color:#cfe3ff}"
        + ".dong{padding:8px 14px;color:var(--nhat);font-size:13px}"
        + "#bao{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);background:var(--the);"
        + "border:1px solid var(--vien);border-radius:9px;padding:9px 14px;display:none}"
        + "</style>"
        + "<header><h1>Kho vật phẩm — bản hồi ức</h1>"
        + "<input id=tim placeholder='tìm theo tên hoặc mã…'>"
        + "<select id=loai></select>"
        + "<span style='flex:1'></span>"
        + "<select id=nv></select><input id=sl type=number value=1 min=1 style='width:70px'>"
        + "<button id=gui>Gửi món đang chọn</button></header>"
        + "<div class=dong id=dong>đang tải…</div><div class=luoi id=luoi></div>"
        + "<div id=bao></div>"
        + "<script>"
        + "let DS=[],CHON=null;"
        + "const $=s=>document.querySelector(s);"
        + "const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));"
        + "function bao(t){const b=$('#bao');b.textContent=t;b.style.display='block';"
        + "clearTimeout(b._t);b._t=setTimeout(()=>b.style.display='none',4000)}"
        + "async function tai(){const r=await fetch('/api/mon');DS=await r.json();"
        + "const ls=[...new Set(DS.map(m=>m.loai))].sort((a,b)=>a-b);"
        + "$('#loai').innerHTML='<option value=\"\">mọi loại</option>'+ls.map(l=>`<option value=${l}>loại ${l}</option>`).join('');"
        + "const r2=await fetch('/api/nguoi');const ng=await r2.json();"
        + "$('#nv').innerHTML=ng.map(n=>`<option value=${n.id}>${esc(n.ten)} — cấp ${n.cap}${n.online?' (online)':''}</option>`).join('');"
        + "ve()}"
        + "function ve(){const t=$('#tim').value.toLowerCase().trim(),l=$('#loai').value;"
        + "const ds=DS.filter(m=>(!l||String(m.loai)===l)&&(!t||m.ten.toLowerCase().includes(t)||String(m.id)===t));"
        + "$('#dong').textContent=`${ds.length} món / tổng ${DS.length}` + (CHON?` — đang chọn: ${CHON.ten} (mã ${CHON.id})`:'');"
        + "$('#luoi').innerHTML=ds.slice(0,400).map(m=>`<div class=mon data-id=${m.id}"
        + " style='${CHON&&CHON.id===m.id?'border-color:var(--xanh);box-shadow:0 0 0 2px var(--xanhnen)':''}'>"
        + "<div class=dau><img class=anh src='/anh?icon=${m.icon}&co=2' onerror=\"this.style.visibility='hidden'\">"
        + "<div><div class=ten>${esc(m.ten)}</div>"
        + "<div><span class=the-nho>mã ${m.id}</span><span class=the-nho>loại ${m.loai}</span>"
        + "<span class=the-nho>cấp ${m.cap}</span><span class=the-nho>icon ${m.icon}</span></div></div></div>"
        + "${m.mota?`<div class=mota>${esc(m.mota)}</div>`:''}"
        + "${m.chiSo.length?`<ul>${m.chiSo.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`:''}"
        + "</div>`).join('')+(ds.length>400?'<div class=dong>… còn nữa, hãy lọc bớt</div>':'')}"
        + "document.addEventListener('input',e=>{if(e.target.id==='tim'||e.target.id==='loai')ve()});"
        + "document.addEventListener('click',e=>{const o=e.target.closest('.mon');if(o){"
        + "CHON=DS.find(m=>m.id===Number(o.dataset.id));ve();return}"
        + "if(e.target.id==='gui'){if(!CHON){bao('chưa chọn món nào');return}"
        + "fetch(`/api/tang?nv=${$('#nv').value}&mon=${CHON.id}&sl=${$('#sl').value}`)"
        + ".then(r=>r.json()).then(j=>bao(j.ok||j.loi))}});"
        + "tai();"
        + "</script></html>";
}
